from __future__ import annotations
from pathlib import Path
import logging
import structlog

from ..codegen.cytozoo import CytoZooCodeGenerator
from ..load import load_ode
from ..ode import ODE

logger = structlog.get_logger()


def _banner(source: str) -> str:
    """The provenance header every generated module carries.

    Hand-written headers in the consuming repo are deleted the moment anyone runs
    the documented regeneration command, so the generator has to emit its own.
    """
    # Deferred: gotranx/__init__.py imports this package, so a module-level
    # import of __version__ would be circular.
    from .. import __version__

    return "\n".join(
        [
            f"# Generated by gotranx {__version__} from {source} -- do not hand-edit.",
            "# Regenerate with `gotranx ode2cytozoo` rather than editing this file.",
            "# Requires a CytoZoo providing `resolve_parameter`; no released CytoZoo",
            "# has it yet, so this module needs a development checkout of CytoZoo.",
            "# Top-level names here (`rhs`, `NUM_STATES`, ...) are unqualified, so",
            "# loading several generated models in one session needs each wrapped in",
            "# its own `module`.",
        ]
    )


def get_code(
    ode: ODE,
    model_name: str | None = None,
    v_name: str = "v",
    remove_unused: bool = False,
    source: Path | str | None = None,
) -> str:
    """Generate the CytoZoo cell-model adapter for the ODE

    Parameters
    ----------
    ode : gotranx.ode.ODE
        The ODE
    model_name : str | None, optional
        Name of the generated Julia struct, by default None, which uses the
        ODE's own name in PascalCase. Must be a valid Julia identifier
    v_name : str, optional
        Name of the state holding the transmembrane potential, by default "v"
    remove_unused : bool, optional
        Remove unused variables, by default False
    source : pathlib.Path | str | None, optional
        The source `.ode` file, named in the provenance banner. Only its
        basename is emitted, by default None, which falls back to the ODE's
        name. An absolute path would otherwise leak one machine's layout into
        a committed file

    Returns
    -------
    str
        The CytoZoo adapter code

    Raises
    ------
    gotranx.exceptions.InvalidModelName
        If the model name is not a valid Julia identifier
    gotranx.exceptions.MissingPotentialState
        If no state is named `v_name`
    """
    codegen = CytoZooCodeGenerator(
        ode, model_name=model_name, v_name=v_name, remove_unused=remove_unused, type_stable=True
    )

    source_name = Path(source).name if source is not None else f"{ode.name}.ode"

    comp = [
        _banner(source_name),
        "import CytoZoo",
        "using CytoZoo: AbstractCardiacCellModel, SpatialContext, resolve_parameter",
        "import CytoZoo: num_states, num_parameters, transmembrane_potential_index",
        "import CytoZoo: default_initial_state, state_index, parameter_index",
        "import CytoZoo: state_names, parameter_names",
        "import CytoZoo: num_monitors, monitor_names, monitor_values!",
        f"const NUM_STATES = {len(ode.states)};",
        f"const NUM_PARAMS = {len(ode.parameters)};",
        codegen.initial_parameter_values(),
        codegen.initial_state_values(),
        codegen.rhs(),
        codegen.monitor_values(),
        codegen.adapter(),
    ]
    return codegen._format("\n".join(comp))


def main(
    fname: Path,
    outname: Path | str | None = None,
    model_name: str | None = None,
    v_name: str = "v",
    remove_unused: bool = False,
    remove_singularities: bool = True,
    verbose: bool = False,
) -> None:
    loglevel = logging.DEBUG if verbose else logging.INFO
    structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(loglevel))
    ode = load_ode(fname, remove_singularities=remove_singularities)
    code = get_code(
        ode,
        model_name=model_name,
        v_name=v_name,
        remove_unused=remove_unused,
        source=fname,
    )
    out = fname if outname is None else Path(outname)
    out_name = out.with_suffix(suffix=".jl")
    out_name.write_text(code)
    logger.info(f"Wrote {out_name}")
