site_name: gotranx
site_description: Parser for gotran ode files
strict: true

theme:
  name: "material"
  features:
    - content.code.copy
repo_name: finsberg/gotranx
repo_url: https://github.com/finsberg/gotranx


nav:
  - Home: "README.md"
  - Demos:
    - "demos/cli.md"
  - Grammar: "grammar.md"
  - Contributing:
    - General: "CONTRIBUTING.md"
    - "Code of Conduct": "CODE_OF_CONDUCT.md"
    - "Adding a new languge": new_language.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
